"""Rebuild cached seen-page layout only; preserve all source asset PNG bytes."""
import argparse,hashlib,importlib.util,json,pathlib,shutil,sys,time
from baseline_evidence import run,update_asset_baselines
import paragraph_evidence as pe
HERE=pathlib.Path(__file__).resolve().parent;ROOT=HERE.parents[1];PREV=ROOT/'generic-reflow-v2-localgeometry/code';FLOW=ROOT/'generic-reflow-v2-flow-relations/code'
def load(name,path):
 spec=importlib.util.spec_from_file_location(name,path);mod=importlib.util.module_from_spec(spec);sys.modules[name]=mod;spec.loader.exec_module(mod);return mod
order=load('baseline_previous_order',PREV/'diagnose_native_regions.py');sys.path.insert(0,str(FLOW));relations=load('baseline_previous_relations',FLOW/'diagnose_flow.py');tree=load('baseline_tree_builder',PREV/'build_tree_reader.py');flow=load('baseline_flow_builder',PREV/'build_flow_reader.py')
for builder in [tree,flow]:builder.annotate=pe.annotate;builder.estimate=pe.estimate;builder.can_join=pe.can_join
p=argparse.ArgumentParser();p.add_argument('previous');p.add_argument('prediction');p.add_argument('out');a=p.parse_args();source=pathlib.Path(a.previous);out=pathlib.Path(a.out);start=time.perf_counter();shutil.copytree(source,out);folder=out/'fractions';baseline=run(folder);update_asset_baselines(folder);o=order.diagnose(folder,out/'order');tree.build(folder,out/'order');pred=json.loads(pathlib.Path(a.prediction).read_text());dims=json.loads((pathlib.Path(a.prediction).parent/'model-costs.json').read_text())['native_model_input_size'];relations.diagnose(folder,out/'order',a.prediction,dims,out/'flow');pe.RETURN_TRACE.clear();r=flow.build(folder,out/'order',out/'flow/flow-relations-private.json');(out/'first-line-return-private.json').write_text(json.dumps(pe.RETURN_TRACE,indent=2))
assets=json.loads((folder/'native-unit-assets-private.json').read_text());unchanged=all(hashlib.sha256((folder/item['file']).read_bytes()).digest()==hashlib.sha256((source/'fractions'/item['file']).read_bytes()).digest() for item in assets['results'] if not item.get('empty'));assert unchanged
summary={'scope':'cached seen-page layout rebuild only','baseline_changes':baseline,'native_asset_pixels_unchanged':unchanged,'paragraphs':r['paragraphs'],'objects':r['objects'],'source_unit_bijection':r['source_unit_bijection'],'accepted_first_line_returns':sum(t['accepted'] for t in pe.RETURN_TRACE),'elapsed_seconds':time.perf_counter()-start,'cold_page_cost':False,'reading_acceptance':False};(out/'baseline-rebuild-result.json').write_text(json.dumps(summary,indent=2));print(json.dumps(summary))
