/** Actual shipped UI source/focus smoke with native image decode; not a browser. */
import fs from 'node:fs';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
await import('../../generic-reflow-v2-viewer-entry/code/test_import_smoke.mjs');
const require=createRequire(process.env.SELECTION_TEST_PACKAGE),native=require('@napi-rs/canvas'),doc=globalThis.document,win=globalThis.window,bundle=JSON.parse(fs.readFileSync(process.argv[3])),reader=bundle.pages[0].reader;
// jsdom does not implement the browser's HTMLImageElement.decode on clones.
// Decode those through the same native Canvas library used by the base harness.
win.HTMLImageElement.prototype.decode=async function(){this.nativeImage=await native.loadImage(this.src);Object.defineProperty(this,'naturalWidth',{value:this.nativeImage.width,configurable:true});Object.defineProperty(this,'naturalHeight',{value:this.nativeImage.height,configurable:true});};
const candidates=reader.blocks.flatMap((b,i)=>b.tokens.filter(t=>t.kind==='native_image').map(t=>({index:i,token:t,area:(t.source_pixel_box[2]-t.source_pixel_box[0])*(t.source_pixel_box[3]-t.source_pixel_box[1])}))).sort((a,b)=>b.area-a.area),selected=candidates[0],section=doc.querySelectorAll('section')[selected.index],buttons=[...section.querySelectorAll('button')],focus=buttons.find(b=>b.textContent.startsWith('查看局部')),back=buttons.find(b=>b.textContent==='回原页'),dialog=doc.querySelector('dialog');
assert(focus&&back);doc.getSelection().removeAllRanges();focus.focus();focus.click();for(let i=0;i<250&&!dialog.open;i++)await new Promise(r=>setTimeout(r,20));assert(dialog.open);
const image=dialog.querySelector('img');assert(image);assert.equal(image.src,selected.token.data_uri);assert(parseFloat(image.style.width)>390);assert.equal(image.style.maxWidth,'none');
const fullWidth=image.naturalWidth;doc.querySelector('#close-dialog').click();assert(!dialog.open);assert.equal(dialog.querySelector('.focus').childNodes.length,0);assert.equal(doc.activeElement,focus);
back.focus();back.click();assert(dialog.open);const svg=dialog.querySelector('svg'),box=svg.getAttribute('viewBox').split(' ').map(Number),sourceBox=selected.token.source_pixel_box;assert(box[0]<=sourceBox[0]&&box[1]<=sourceBox[1]&&box[0]+box[2]>=sourceBox[2]&&box[1]+box[3]>=sourceBox[3]);dialog.querySelector('.focus button').click();assert.equal(svg.getAttribute('viewBox'),`0 0 ${bundle.pages[0].source.width} ${bundle.pages[0].source.height}`);doc.querySelector('#close-dialog').click();assert.equal(doc.activeElement,back);assert.equal(doc.querySelectorAll('canvas').length,reader.blocks.length);
console.log(JSON.stringify({scope:'actual shipped-module jsdom/native Canvas usability smoke',figure_focus_contains_exact_native_composite:true,focus_native_width_pixels:fullWidth,focus_larger_than_mobile_width:true,source_region_contains_whole_composite:true,source_full_page_action:true,close_cleans_and_restores_focus:true,reader_preserved:true,browser_verified:false}));
