/** Separate geometric coverage evidence; it does not certify mixed-engine pixels. */
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {compileResources,layoutBlocks} from './reader_engine.mjs';
const [runtime,input,out]=process.argv.slice(2),require=createRequire(path.resolve(runtime,'package.json')),canvas=require('@napi-rs/canvas'),data=JSON.parse(fs.readFileSync(input)),paths=compileResources(data,canvas.Path2D),ctx=canvas.createCanvas(1,1).getContext('2d'),seen=new Set(),overflows=[],bounds=[];
for(const block of data.blocks)for(const token of block.tokens){if(token.kind!=='vector')continue;let box=[Infinity,Infinity,-Infinity,-Infinity];for(const id of token.native_event_ids){if(seen.has(id))throw Error('duplicate native glyph paint in reading output');seen.add(id);const e=data.events[id];ctx.setTransform(1,0,0,1,0,0);for(const op of data.affine_programs[e.program])ctx[op.name](...op.args);ctx.translate(e.x,e.y);ctx.scale(e.fontSize,-e.fontSize);const p=new canvas.Path2D();p.addPath(paths[e.resource],ctx.getTransform());const b=p.computeTightBounds();box=[Math.min(box[0],b[0]),Math.min(box[1],b[1]),Math.max(box[2],b[2]),Math.max(box[3],b[3])];}const r=token.source_pixel_box,overflow=Math.max(r[0]-box[0],r[1]-box[1],box[2]-r[2],box[3]-r[3],0);if(overflow>0)overflows.push({token:token.id,overflow_source_pixels:overflow,native_path_box:box,layout_box:r});bounds.push({token:token.id,box});}
const contacts=[];for(let i=0;i<bounds.length;i++)for(let j=i+1;j<bounds.length;j++){const a=bounds[i],b=bounds[j],w=Math.min(a.box[2],b.box[2])-Math.max(a.box[0],b.box[0]),h=Math.min(a.box[3],b.box[3])-Math.max(a.box[1],b.box[1]);if(w>0&&h>0)contacts.push({a:a.token,b:b.token,box_intersection_area:w*h});}

const byToken=new Map(bounds.map(x=>[x.token,x.box]));const outputGeometry=[];
for(const font of [20,28]){let clipped=[],contacts=[];for(const block of layoutBlocks(data,font,390)){const ink=[];for(const p of block.placements){const t=p.token,b=t.kind==='vector'?byToken.get(t.id):t.asset_pixel_box.map(x=>x/t.asset_scale*data.source_capture_scale),s=p.fontScale/data.body_font_pdf/data.source_capture_scale;const box=[p.x+(b[0]-t.source_pixel_box[0])*s,p.y+(b[1]-t.source_pixel_box[1])*s,p.x+(b[2]-t.source_pixel_box[0])*s,p.y+(b[3]-t.source_pixel_box[1])*s];if(box[0]<0||box[1]<0||box[2]>block.width||box[3]>block.height)clipped.push({block:block.index,token:t.id,box});ink.push({token:t.id,kind:t.kind,box});}for(let i=0;i<ink.length;i++)for(let j=i+1;j<ink.length;j++){const a=ink[i],b=ink[j],w=Math.min(a.box[2],b.box[2])-Math.max(a.box[0],b.box[0]),h=Math.min(a.box[3],b.box[3])-Math.max(a.box[1],b.box[1]);if(w>0&&h>0)contacts.push({block:block.index,a:a.token,b:b.token,kinds:[a.kind,b.kind],box_intersection_area:w*h});}}outputGeometry.push({font_css:font,viewport_css:390,contour_or_asset_boxes_outside_canvas:clipped,contour_or_asset_box_contacts:contacts});}
const result={output_geometry:outputGeometry,emitted_native_paints:seen.size,payload_native_paints:Object.keys(data.events).length,unique_paint_id_complete:seen.size===Object.keys(data.events).length,vector_token_count:bounds.length,source_contour_box_overflows:overflows,cross_vector_token_contour_box_contacts:contacts,source_geometry_checked:true,mixed_native_image_vector_pixel_ownership_proven:false,pixel_completeness_not_inferred_from_ids:true};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({...result,output_geometry:outputGeometry.map(x=>({...x,contour_or_asset_boxes_outside_canvas:x.contour_or_asset_boxes_outside_canvas.length,contour_or_asset_box_contacts:x.contour_or_asset_box_contacts.length})),source_contour_box_overflows:overflows.length,cross_vector_token_contour_box_contacts:contacts.length}));
