"""Package a private interactive prototype; execution in a browser is unverified."""
import argparse,json,pathlib
p=argparse.ArgumentParser();p.add_argument('reader');p.add_argument('out');a=p.parse_args();data=pathlib.Path(a.reader).read_text();engine=pathlib.Path(__file__).with_name('reader_engine.mjs').read_text().replace('export ','');out=pathlib.Path(a.out);out.parent.mkdir(parents=True,exist_ok=True)
script=engine+r'''
const data=JSON.parse(document.querySelector('#reader-data').textContent()),paths=compileResources(data,Path2D),images=new Map(),main=document.querySelector('main'),status=document.querySelector('#status'),dialog=document.querySelector('dialog');
for(const block of data.blocks)for(const token of block.tokens)if(token.kind==='native_image'&&!images.has(token.id)){const image=new Image();image.src=token.data_uri;await image.decode();images.set(token.id,image);}
function render(){const font=Number(document.querySelector('select').value),dpr=window.devicePixelRatio||1,width=Math.min(390,window.innerWidth),layouts=layoutBlocks(data,font,width);if(layouts.reduce((n,b)=>n+b.width*b.height*dpr*dpr,0)>DEFAULT_LAYOUT.maximumCanvasPixels){status.textContent='当前字号/DPR 超过画布缓存预算，已停止重绘。';return;}main.replaceChildren();let under=0;for(const block of layouts){const canvas=document.createElement('canvas');canvas.width=Math.ceil(block.width*dpr);canvas.height=Math.ceil(block.height*dpr);canvas.style.width=block.width+'px';canvas.style.height=block.height+'px';canvas.setAttribute('aria-label','原生字形视觉段落，选择文字尚未接入');const report=drawBlock(canvas.getContext('2d'),block,data,paths,images,dpr);under+=report.undersampled_local_images;canvas.onclick=event=>{const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*block.width/rect.width,y=(event.clientY-rect.top)*block.height/rect.height,p=block.placements.find(p=>p.token.kind==='native_image'&&x>=p.x&&x<=p.x+p.width&&y>=p.y&&y<=p.y+p.height);if(!p)return;const image=images.get(p.token.id).cloneNode();image.style.width=(image.naturalWidth/dpr)+'px';image.style.maxWidth='none';dialog.querySelector('.focus').replaceChildren(image);dialog.showModal();};main.append(canvas);}status.textContent=under?'有 '+under+' 个局部图像需要按当前字号/DPR 重新采样。':'当前局部图像的采样密度足够；文字选择、实际浏览器表现尚未验收。';}
document.querySelector('select').onchange=render;document.querySelector('dialog button').onclick=()=>dialog.close();render();
'''
html='''<!doctype html><html lang="zh"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Native-resource paper reflow research preview</title><style>body{margin:0;background:#f2f2f2;font:14px sans-serif}header{padding:12px;max-width:760px;margin:auto}main{max-width:390px;margin:auto;background:white}canvas{display:block}dialog{max-width:90vw;max-height:90vh;background:white}.focus{max-width:85vw;max-height:75vh;overflow:auto}.focus img{display:block}select{font:inherit}</style></head><body><header>研究预览：共享原生字形绘制，局部公式/图保留原生资产。<br><label>正文字号 <select><option value="20">20 px</option><option value="24">24 px</option><option value="28">28 px</option></select></label><p>文字选择/复制尚未接入。点击局部原生图像可在原采样范围内查看；该交互尚未经过浏览器实测。</p><p id="status"></p></header><main></main><dialog><button>关闭</button><p>原始局部采样，超出窗口可滚动。</p><div class="focus"></div></dialog>'''
html+='<script id="reader-data" type="application/json">'+data.replace('<','\\u003c')+'</script><script type="module">'+script+'</script></body></html>';out.write_text(html);print(json.dumps({'html_bytes':out.stat().st_size,'external_resource_requests':0,'canvas_paragraph_elements':len(json.loads(data)['blocks']),'browser_verified':False}))
