/** Strict device-translation control at each actually requested child scale. */
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {compileResources,layoutBlocks,drawBlock} from './reader_engine.mjs';
const [runtime,input,out]=process.argv.slice(2),require=createRequire(path.resolve(runtime,'package.json')),canvas=require('@napi-rs/canvas'),data=JSON.parse(fs.readFileSync(input)),paths=compileResources(data,canvas.Path2D),images=new Map(),results=[];
for(const b of data.blocks)for(const t of b.tokens)if(t.kind==='native_image'&&!images.has(t.id))images.set(t.id,await canvas.loadImage(t.data_uri));
for(const [font,dpr] of [[20,1],[28,2]])for(const b of layoutBlocks(data,font,390).filter(b=>b.kind==='formula'))for(const p of b.placements){
 const width=Math.ceil(p.width+100),height=Math.ceil(p.height+100),make=(shift)=>{const c=canvas.createCanvas(width*dpr,height*dpr);const q={...p,x:20.25+shift/dpr,y:20.25};const stats=drawBlock(c.getContext('2d'),{...b,width,height,placements:[q]},data,paths,images,dpr);return {a:c.getContext('2d').getImageData(0,0,c.width,c.height).data,stats};},base=make(0),shifted=make(3);let diff=0,maxDelta=0;
 for(let y=0;y<height*dpr;y++)for(let x=0;x<width*dpr-3;x++){let changed=false;for(let c=0;c<4;c++){const delta=Math.abs(base.a[(y*width*dpr+x)*4+c]-shifted.a[(y*width*dpr+x+3)*4+c]);maxDelta=Math.max(maxDelta,delta);if(delta)changed=true;}if(changed)diff++;}
 results.push({font_css:font,dpr,block:b.index,token:p.token.id,role:p.token.formula_role,kind:p.token.kind,source_members:p.token.members,font_scale:p.fontScale,device_translation_px:3,different_pixels:diff,max_channel_delta:maxDelta,under_sampled:base.stats.undersampled_local_images,original_child_resource_unchanged:true,source_glyph_geometry_uniform:true});
}
const result={method:'same child native resource at actual output scale, shifted exactly 3 device pixels in isolated native canvas',children:results,strict_integer_translation_pass:results.every(x=>!x.different_pixels),all_sampled_at_target:results.every(x=>!x.under_sampled),not_full_page_pixel_ownership_proof:true};fs.writeFileSync(out,JSON.stringify(result,null,2));console.log(JSON.stringify({children:results.length,strict_integer_translation_pass:result.strict_integer_translation_pass,all_sampled_at_target:result.all_sampled_at_target,different_pixels:results.map(x=>x.different_pixels)}));
