"""Aggregate only; never publish source text, glyph contours or native identifiers."""
import argparse,json,pathlib,base64
p=argparse.ArgumentParser();p.add_argument('root');p.add_argument('out');a=p.parse_args();root=pathlib.Path(a.root);rows=[]
for n in ['H5','H6']:
 current=root/'generic-reflow-v2-formula-hierarchy-local'/(n+'-candidate-2');previous=root/'generic-reflow-v2-baseline-evidence-local'/(n+'-reader');data=json.loads((current/'reader-data-private.json').read_text());trace=json.loads((current/'formula-trace-private.json').read_text());moved=json.loads((current/'moved-audit-private.json').read_text());geom=json.loads((current/'geometry-audit-private.json').read_text());sizes=[]
 for font in [20,28]:
  old=json.loads((previous/('reader-'+str(font))/'layout-private.json').read_text());new=json.loads((current/('reader-'+str(font))/'layout-private.json').read_text());olddata=json.loads((previous/'final/reader-data-private.json').read_text());lookup={t['id']:t for b in olddata['blocks'] for t in b['tokens']};oldplacement={uid:p for b in old for p in b['placements'] for uid in lookup[p['token']['id']]['members']}
  for b in new:
   if b['kind']!='formula':continue
   match=next(t for t in data['blocks'][b['index']]['tokens'] if t['formula_role']=='core');unit=match['members'][0];before=oldplacement[unit]['fontScale'];after=b['placements'][0]['fontScale'];sizes.append({'font_css':font,'formula_ordinal':len([x for x in sizes if x['font_css']==font]),'prior_core_font_scale':before,'new_core_font_scale':after,'relative_linear_scale':after/before,'number_mode':b['formula_layout']['mode']})
 tokens=[t for b in data['blocks'] for t in b['tokens']];ims=[t for t in tokens if t['kind']=='native_image'];r={'diagnostic':n,'previously_seen':True,'formula_hierarchies':len(trace['applied']),'native_units':trace['native_unit_count'],'native_unit_multiset_unchanged':True,'exact_original_composite_reconstructions':sum('target_grid_rgba_different_pixels' in x for x in trace['applied']),'composite_different_pixels':sum(x.get('target_grid_rgba_different_pixels',0) for x in trace['applied']),'payload_bytes':(current/'reader-data-private.json').stat().st_size,'previous_payload_bytes':(previous/'final/reader-data-private.json').stat().st_size,'blocks':len(data['blocks']),'vector_tokens':sum(t['kind']=='vector' for t in tokens),'local_image_tokens':len(ims),'local_image_png_bytes':sum(len(base64.b64decode(t['data_uri'].split(',')[1])) for t in ims),'shared_contours':len(data['resources']),'glyph_paints':len(data['events']),'hierarchy_builder_measured_wall_seconds_only':trace['elapsed_seconds'],'cold_page_cost_measured':False,'core_scales':sizes,'integer_translation_different_pixels':[x['different_pixels'] for x in moved['children']],'integer_translation_max_channel_delta':max(x['max_channel_delta'] for x in moved['children']),'strict_integer_translation_pass':moved['strict_integer_translation_pass'],'actual_scale_sampling_pass':moved['all_sampled_at_target'],'output_geometry':[{'font_css':x['font_css'],'outside_canvas':len(x['contour_or_asset_boxes_outside_canvas']),'contacts':len(x['contour_or_asset_box_contacts'])} for x in geom['output_geometry']],'source_vector_contour_overflow_count_retained':len(geom['source_contour_box_overflows']),'full_visual_review_bands':{'20':len(list((current/'visual-20').glob('band-*.png'))),'28':len(list((current/'visual-28').glob('band-*.png')))},'mixed_engine_pixel_ownership_proven':False,'browser_verified':False,'selection_verified':False,'whole_page_acceptance':False};rows.append(r)
result={'candidate':'formula-hierarchy-2','controls':{'relations':16,'layout_cases':18},'new_holdouts_opened':0,'blind_batch_result_unchanged':'0/2','pages':rows,'new_ci_runs':0,'full_cold_page_previous_failures_unchanged':True};pathlib.Path(a.out).write_text(json.dumps(result,indent=2));print(json.dumps(result,indent=2))
