/** Pinned renderer-resource observation; no product files or PDF text are rewritten. */
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
const [runtime,pdf,out]=process.argv.slice(2);if(!out)throw Error('runtime pdf private-output required');fs.mkdirSync(out,{recursive:true});
const require=createRequire(path.resolve(runtime,'package.json'));const canvas=require('@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,Path2D:canvas.Path2D,ImageData:canvas.ImageData});
const root=path.resolve(runtime,'node_modules/pdfjs-dist');const originalFile=path.join(root,'legacy/build/pdf.mjs');const original=fs.readFileSync(originalFile,'utf8');const sha=s=>crypto.createHash('sha256').update(s).digest('hex');
const target='    const fontSize = current.fontSize / current.fontSizeScale;';if(original.split(target).length!==2)throw Error('pinned paintChar hook anchor changed');
const hook=`${target}
    const __g = this.__readestCurrentGlyph;
    const __event = { opIdx, glyphOrdinal: this.__readestGlyphOrdinal, originalCharCode: __g?.originalCharCode, character, unicodeCandidate: __g?.fontChar === character ? __g.unicode : null, glyphKeys: __g ? Object.keys(__g) : [], loadedName: font.loadedName, fontSize, x, y, transform: Array.from(ctx.getTransform().toFloat64Array()).filter((_,i)=>[0,1,4,5,12,13].includes(i)), fillStyle: typeof ctx.fillStyle === 'string' ? ctx.fillStyle : null, alpha: ctx.globalAlpha, blend: ctx.globalCompositeOperation, textRenderingMode: current.textRenderingMode, pattern: !!(current.patternFill || current.patternStroke), missingFile: !!font.missingFile, fontDataBytes: font.data?.byteLength ?? 0, canvasWidth: ctx.canvas.width, canvasHeight: ctx.canvas.height };
    try { __event.path = this.commonObjs.get(font.loadedName + '_path_' + character)?.path; } catch {}
    if (globalThis.__readestGlyphHook?.(__event) === false) return;`;
let instrumented=original.replace(target,hook);const anchor='      const character = glyph.fontChar;';if(instrumented.split(anchor).length!==2)throw Error('pinned showText glyph hook changed');instrumented=instrumented.replace(anchor,anchor+'\n      this.__readestCurrentGlyph = glyph; this.__readestGlyphOrdinal = i;');
const instrumentedFile=path.join(root,'legacy/build/pdf.readest-resource-probe.mjs');fs.writeFileSync(instrumentedFile,instrumented);
const lib=await import(pathToFileURL(instrumentedFile));lib.GlobalWorkerOptions.workerSrc=pathToFileURL(path.join(root,'legacy/build/pdf.worker.mjs')).href;
const begin=performance.now();const task=lib.getDocument({data:new Uint8Array(fs.readFileSync(pdf)),disableFontFace:true,fontExtraProperties:true,useSystemFonts:false,isEvalSupported:false,enableXfa:false,standardFontDataUrl:path.join(root,'standard_fonts/')});const doc=await task.promise;const page=await doc.getPage(1);const ops=await page.getOperatorList({annotationMode:lib.AnnotationMode.DISABLE});const view=page.getViewport({scale:2});const resources=new Map();let events=[];
async function render(name,capture,skip){const c=canvas.createCanvas(Math.ceil(view.width),Math.ceil(view.height));globalThis.__readestGlyphHook=e=>{if(capture){const raw=e.path ? Array.from(e.path) : null;const key=e.loadedName+':'+e.character;if(raw&&!resources.has(key))resources.set(key,raw);events.push({...e,path:undefined,id:events.length,resource:raw?key:null});}return !skip;};await page.render({canvasContext:c.getContext('2d'),viewport:view,annotationMode:lib.AnnotationMode.DISABLE}).promise;fs.writeFileSync(path.join(out,name+'.png'),c.toBuffer('image/png'));return c;}
const baseline=await render('baseline',true,false);const without=await render('without-captured-glyph-paints',false,true);globalThis.__readestGlyphHook=null;
function buildPath(commands){const p=new canvas.Path2D();for(let i=0;i<commands.length;){const op=commands[i++];if(op===0)p.moveTo(commands[i++],commands[i++]);else if(op===1)p.lineTo(commands[i++],commands[i++]);else if(op===2)p.bezierCurveTo(...commands.slice(i,i+=6));else if(op===3)p.quadraticCurveTo(...commands.slice(i,i+=4));else if(op===4)p.closePath();else throw Error('unknown pinned native glyph path opcode');}return p;}
const replay=canvas.createCanvas(baseline.width,baseline.height),rc=replay.getContext('2d');rc.drawImage(without,0,0);const pathCache=new Map();
for(const e of events){if(!e.resource||e.pattern||e.missingFile||e.textRenderingMode!==0||e.blend!=='source-over'||!e.fillStyle)continue;if(!pathCache.has(e.resource))pathCache.set(e.resource,buildPath(resources.get(e.resource)));rc.save();rc.setTransform(...e.transform);rc.globalAlpha=e.alpha;rc.globalCompositeOperation=e.blend;rc.fillStyle=e.fillStyle;rc.translate(e.x,e.y);rc.scale(e.fontSize,-e.fontSize);rc.fill(pathCache.get(e.resource));rc.restore();}
fs.writeFileSync(path.join(out,'glyph-resource-replay-over-nontext.png'),replay.toBuffer('image/png'));
function differences(a,b){const x=a.getContext('2d').getImageData(0,0,a.width,a.height).data,y=b.getContext('2d').getImageData(0,0,b.width,b.height).data;let pixels=0,max=0;for(let i=0;i<x.length;i+=4){let changed=false;for(let c=0;c<4;c++){const d=Math.abs(x[i+c]-y[i+c]);if(d)changed=true;max=Math.max(max,d);}if(changed)pixels++;}return {pixels,max};}
const glyphReplayDifference=differences(baseline,replay);
const originalLib=await import(pathToFileURL(originalFile));originalLib.GlobalWorkerOptions.workerSrc=pathToFileURL(path.join(root,'legacy/build/pdf.worker.mjs')).href;const originalTask=originalLib.getDocument({data:new Uint8Array(fs.readFileSync(pdf)),disableFontFace:true,fontExtraProperties:true,useSystemFonts:false,isEvalSupported:false,enableXfa:false,standardFontDataUrl:path.join(root,'standard_fonts/')});const originalDoc=await originalTask.promise;const originalPage=await originalDoc.getPage(1);const untouched=canvas.createCanvas(baseline.width,baseline.height);await originalPage.render({canvasContext:untouched.getContext('2d'),viewport:originalPage.getViewport({scale:2}),annotationMode:originalLib.AnnotationMode.DISABLE}).promise;const observerDifference=differences(baseline,untouched);await originalTask.destroy();
const unsupported=events.filter(e=>!e.resource||e.pattern||e.missingFile||e.textRenderingMode!==0||e.blend!=='source-over'||!e.fillStyle||e.canvasWidth!==baseline.width||e.canvasHeight!==baseline.height);
const result={engine:'PDF.js '+lib.version+' legacy build with @napi-rs/canvas; native Node renderer, not browser',sourceSha256:sha(fs.readFileSync(pdf)),upstreamPdfModuleSha256:sha(original),instrumentedModuleSha256:sha(instrumented),sourcePdfBytes:fs.statSync(pdf).size,operatorCount:ops.fnArray.length,glyphPaintCalls:events.length,uniqueNativeGlyphPaths:resources.size,resourceJsonBytes:Buffer.byteLength(JSON.stringify(Object.fromEntries(resources))),eventJsonBytes:Buffer.byteLength(JSON.stringify(events)),fontIds:[...new Set(events.map(e=>e.loadedName))].length,fontCharDiffersFromUnicode:events.filter(e=>e.unicodeCandidate!==null&&e.unicodeCandidate!==e.character).length,unsupportedPaintCalls:unsupported.length,glyphRecordKeys:[...new Set(events.flatMap(e=>e.glyphKeys))],seconds: (performance.now()-begin)/1000,observerDifference,glyphReplayDifference,originalPositionReconstructionVerified:glyphReplayDifference.pixels===0&&unsupported.length===0,paintOrderScope:'glyphs replayed after all nontext; overlaps can invalidate this restricted probe',relocationVerified:false,semanticUnicodeCertified:false,holdoutsOpened:0};
fs.writeFileSync(path.join(out,'glyph-resources-private.json'),JSON.stringify(Object.fromEntries(resources)));fs.writeFileSync(path.join(out,'glyph-paints-private.json'),JSON.stringify(events));fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await task.destroy();
