/** Restricted vector resource/state diagnostic. Private evidence only. */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
import {trackState,matrix} from './state_tracker.mjs';
const [runtime,pdf,out]=process.argv.slice(2);if(!out)throw Error('runtime pdf private-output required');fs.mkdirSync(out,{recursive:true});
const require=createRequire(path.resolve(runtime,'package.json'));const canvas=require('@napi-rs/canvas');Object.assign(globalThis,{DOMMatrix:canvas.DOMMatrix,Path2D:canvas.Path2D,ImageData:canvas.ImageData});
const root=path.resolve(runtime,'node_modules/pdfjs-dist'),originalFile=path.join(root,'legacy/build/pdf.mjs'),original=fs.readFileSync(originalFile,'utf8'),sha=s=>crypto.createHash('sha256').update(s).digest('hex');
function patch(s,anchor,replacement){if(s.split(anchor).length!==2)throw Error('pinned hook changed: '+anchor);return s.replace(anchor,replacement);}
let instrumented=patch(original,'  showText(opIdx, glyphs) {',`  showText(opIdx, glyphs) {
    globalThis.__readestTextHook?.({opIdx, glyphs, type3:!!this.current.font.isType3Font, invalid:!!this.current.font.isInvalidPDFjsFont, fontSize:this.current.fontSize, visible:this.contentVisible, missingFile:!!this.current.font.missingFile, disableFontFace:!!this.current.font.disableFontFace, mode:this.current.textRenderingMode});`);
instrumented=patch(instrumented,'      const character = glyph.fontChar;','      const character = glyph.fontChar;\n      this.__readestCurrentGlyph = glyph; this.__readestGlyphOrdinal = i;');
const anchor='    const fontSize = current.fontSize / current.fontSizeScale;';instrumented=patch(instrumented,anchor,`${anchor}
    const __g=this.__readestCurrentGlyph, __m=ctx.getTransform();let __path;
    try { __path=this.commonObjs.get(font.loadedName+'_path_'+character)?.path; } catch {}
    if(globalThis.__readestGlyphHook?.({opIdx, glyphOrdinal:this.__readestGlyphOrdinal, originalCharCode:__g?.originalCharCode, character, unicodeCandidate:__g?.fontChar===character?__g.unicode:null, loadedName:font.loadedName, fontSize, x, y, transform:[__m.a,__m.b,__m.c,__m.d,__m.e,__m.f], canonicalFillColor:typeof current.fillColor==='string'?current.fillColor:null, getterFillStyle:ctx.fillStyle, textRenderingMode, pattern:!!(current.patternFill||current.patternStroke), missingFile:!!font.missingFile, activeSMask:!!current.activeSMask, path:__path},ctx)===false)return;`);
instrumented=patch(instrumented,'            this[fnId](i);','            globalThis.__readestBeforeOperator?.(); this[fnId](i);');
instrumented=patch(instrumented,'            this[fnId](i, ...fnArgs);','            globalThis.__readestBeforeOperator?.(); this[fnId](i, ...fnArgs);');
const file=path.join(root,'legacy/build/pdf.readest-stateful-probe.mjs');fs.writeFileSync(file,instrumented);const lib=await import(pathToFileURL(file));lib.GlobalWorkerOptions.workerSrc=pathToFileURL(path.join(root,'legacy/build/pdf.worker.mjs')).href;
const begin=performance.now(),options={data:new Uint8Array(fs.readFileSync(pdf)),disableFontFace:true,fontExtraProperties:true,useSystemFonts:false,isEvalSupported:false,enableXfa:false,standardFontDataUrl:path.join(root,'standard_fonts/')},task=lib.getDocument(options),doc=await task.promise,page=await doc.getPage(1),ops=await page.getOperatorList({annotationMode:lib.AnnotationMode.DISABLE}),view=page.getViewport({scale:2});
const resources=new Map(),clipResources=new Map(),events=[],texts=[],unsupported=[];let capture=false,skip=false;
function buildPath(commands){const p=new canvas.Path2D();for(let i=0;i<commands.length;){const op=commands[i++];if(op===0)p.moveTo(commands[i++],commands[i++]);else if(op===1)p.lineTo(commands[i++],commands[i++]);else if(op===2)p.bezierCurveTo(...commands.slice(i,i+=6));else if(op===3)p.quadraticCurveTo(...commands.slice(i,i+=4));else if(op===4)p.closePath();else throw Error('unknown native path command');}return p;}
async function render(name,doCapture,doSkip){capture=doCapture;skip=doSkip;const c=canvas.createCanvas(Math.ceil(view.width),Math.ceil(view.height));const ctx=trackState(c.getContext('2d'),canvas.Path2D);
 globalThis.__readestTextHook=e=>{if(capture){const glyphs=e.glyphs.filter(g=>typeof g!=='number');const eligible=e.fontSize!==0&&e.visible&&!e.type3&&!e.invalid;const expected=eligible?glyphs.reduce((n,g)=>n+((g.isInFont||e.missingFile)?(g.accent?2:1):0),0):0;texts.push({...e,glyphs:undefined,glyphRecords:glyphs.length,expectedPaintCalls:expected});}};
 globalThis.__readestGlyphHook=(e,nativeCtx)=>{if(capture){const state=nativeCtx.__readestState?.();const key=e.loadedName+':'+e.character;if(e.path&&!resources.has(key))resources.set(key,{commands:Array.from(e.path),native:buildPath(Array.from(e.path))});const clips=(state?.clips??[]).map(c=>{const k=sha(c.svg);if(!clipResources.has(k))clipResources.set(k,{svg:c.svg,native:c.path});return {resource:k,rule:c.rule,transform:c.transform,affine:c.affine,absoluteTransform:c.absoluteTransform};});const event={...e,path:undefined,id:events.length,resource:e.path?key:null,state:state?{...state,clips}:null};events.push(event);if(!e.path||e.pattern||e.missingFile||e.activeSMask||e.textRenderingMode!==0||!state||state.blend!=='source-over'||state.filter!=='none'||typeof state.fillStyle!=='string')unsupported.push(event.id);}return !skip;};
 await page.render({canvasContext:ctx,viewport:view,annotationMode:lib.AnnotationMode.DISABLE}).promise;fs.writeFileSync(path.join(out,name+'.png'),c.toBuffer('image/png'));return c;}
const baseline=await render('baseline',true,false),without=await render('without-glyph-paints',false,true);globalThis.__readestTextHook=globalThis.__readestGlyphHook=null;
function applyAffine(ctx,delta,state,fallback){ctx.setTransform(...delta);if(!state.absoluteTransform&&state.affine){for(const op of state.affine)ctx[op.name](...op.args);}else ctx.transform(...(fallback??state.transform));}
function drawGlyph(ctx,e,delta=[1,0,0,1,0,0],serializedClip=false){const state=e.state;if(!state||!e.resource)return;ctx.save();for(const c of state.clips){applyAffine(ctx,delta,c);ctx.clip(serializedClip?new canvas.Path2D(clipResources.get(c.resource).svg):clipResources.get(c.resource).native,c.rule);}applyAffine(ctx,delta,state,e.transform);ctx.fillStyle=state.fillStyle;ctx.globalAlpha=state.alpha;ctx.globalCompositeOperation=state.blend;ctx.filter=state.filter;ctx.translate(e.x,e.y);ctx.scale(e.fontSize,-e.fontSize);ctx.fill(resources.get(e.resource).native);ctx.restore();}
function diff(a,b){const x=a.getContext('2d').getImageData(0,0,a.width,a.height).data,y=b.getContext('2d').getImageData(0,0,b.width,b.height).data;let pixels=0,max=0;for(let i=0;i<x.length;i+=4){let changed=false;for(let c=0;c<4;c++){const d=Math.abs(x[i+c]-y[i+c]);if(d)changed=true;max=Math.max(max,d);}if(changed)pixels++;}return {pixels,max};}
function replay(name,serializedClip){const c=canvas.createCanvas(baseline.width,baseline.height),ctx=c.getContext('2d');ctx.drawImage(without,0,0);for(const e of events)if(!unsupported.includes(e.id))drawGlyph(ctx,e,[1,0,0,1,0,0],serializedClip);fs.writeFileSync(path.join(out,name+'.png'),c.toBuffer('image/png'));return c;}
const nativeReplay=replay('native-clip-replay',false),serializedReplay=replay('serialized-clip-replay',true);
const originalLib=await import(pathToFileURL(originalFile));originalLib.GlobalWorkerOptions.workerSrc=pathToFileURL(path.join(root,'legacy/build/pdf.worker.mjs')).href;const originalTask=originalLib.getDocument({...options,data:new Uint8Array(fs.readFileSync(pdf))}),originalDoc=await originalTask.promise,originalPage=await originalDoc.getPage(1),untouched=canvas.createCanvas(baseline.width,baseline.height);await originalPage.render({canvasContext:untouched.getContext('2d'),viewport:originalPage.getViewport({scale:2}),annotationMode:originalLib.AnnotationMode.DISABLE}).promise;const observerDifference=diff(baseline,untouched);await originalTask.destroy();
// Select one native text-show interval by size, with no source-name/string tuning.
// This is a text-only bounded mechanism, not proof of complete inline-math ownership.
const groups=new Map();for(const e of events){if(unsupported.includes(e.id)||e.state.clips.length||e.state.absoluteTransform)continue;if(!groups.has(e.opIdx))groups.set(e.opIdx,[]);groups.get(e.opIdx).push(e);}
const selected=[...groups.values()].filter(g=>g.length>=2).sort((a,b)=>b.length-a.length||a[0].opIdx-b[0].opIdx)[0];const relocation=[];
if(selected){
 let bounds=[Infinity,Infinity,-Infinity,-Infinity];for(const e of selected){const p=new canvas.Path2D();p.addPath(resources.get(e.resource).native,new canvas.DOMMatrix(e.transform).translate(e.x,e.y).scale(e.fontSize,-e.fontSize));const b=p.computeTightBounds();bounds=[Math.min(bounds[0],b[0]),Math.min(bounds[1],b[1]),Math.max(bounds[2],b[2]),Math.max(bounds[3],b[3])];}
 const selectedKeys=new Set(selected.map(e=>e.opIdx+':'+e.glyphOrdinal+':'+e.character));
 for(const scale of [1,3]){
  const delta=[scale,0,0,scale,8-bounds[0]*scale,8-bounds[1]*scale],w=Math.ceil((bounds[2]-bounds[0])*scale)+16,h=Math.ceil((bounds[3]-bounds[1])*scale)+16;
  const resourceCanvas=canvas.createCanvas(w,h),resourceContext=resourceCanvas.getContext('2d');for(const e of selected)drawGlyph(resourceContext,e,delta,true);
  const reference=canvas.createCanvas(w,h),referenceContext=reference.getContext('2d');let selectedActive=false,nativeCalls=0;const paintMethods=['fill','stroke','fillRect','strokeRect','fillText','strokeText','drawImage','putImageData'];
  for(const name of paintMethods){const originalPaint=referenceContext[name].bind(referenceContext);referenceContext[name]=(...args)=>{if(selectedActive)return originalPaint(...args);};}
  globalThis.__readestGlyphHook=(e,ctx)=>{selectedActive=selectedKeys.has(e.opIdx+':'+e.glyphOrdinal+':'+e.character);if(selectedActive)nativeCalls++;return selectedActive;};globalThis.__readestTextHook=()=>{selectedActive=false;};
  // Reset before all non-text PDF operators so later strokes cannot leak in.
  // The pinned engine calls this exact dispatch; see instrumentation above.
  globalThis.__readestBeforeOperator=()=>{selectedActive=false;};
  await page.render({canvas:null,canvasContext:referenceContext,viewport:view,transform:delta,background:'rgba(0,0,0,0)',annotationMode:lib.AnnotationMode.DISABLE}).promise;
  globalThis.__readestGlyphHook=globalThis.__readestTextHook=globalThis.__readestBeforeOperator=null;
  fs.writeFileSync(path.join(out,'relocated-resource-'+scale+'.png'),resourceCanvas.toBuffer('image/png'));fs.writeFileSync(path.join(out,'relocated-native-'+scale+'.png'),reference.toBuffer('image/png'));
  relocation.push({scale,delta,width:w,height:h,glyphs:selected.length,nativeCalls,resourceCount:new Set(selected.map(e=>e.resource)).size,difference:diff(resourceCanvas,reference)});
 }
}
const counters={showTextCalls:texts.length,glyphRecords:texts.reduce((n,x)=>n+x.glyphRecords,0),expectedObservedPaintCalls:texts.reduce((n,x)=>n+x.expectedPaintCalls,0),observedPaintCalls:events.length,type3Calls:texts.filter(x=>x.type3).length,invalidFontCalls:texts.filter(x=>x.invalid).length,zeroFontCalls:texts.filter(x=>x.fontSize===0).length,unsupportedPaintCalls:unsupported.length};
const result={engine:'PDF.js 6.2.108 legacy + native Node canvas, not browser',sourceSha256:sha(fs.readFileSync(pdf)),upstreamSha256:sha(original),instrumentedSha256:sha(instrumented),operatorCount:ops.fnArray.length,counters,resourceCount:resources.size,clipResourceCount:clipResources.size,absoluteTransformGlyphs:events.filter(e=>e.state?.absoluteTransform).length,stateGetterColorMismatch:events.filter(e=>e.state?.fillStyle!==e.getterFillStyle).length,observerDifference,nativeClipReplayDifference:diff(baseline,nativeReplay),serializedClipReplayDifference:diff(nativeReplay,serializedReplay),replayScope:'all observed glyphs after nontext; original draw order not reconstructed',relocation,relocationVerified:relocation.length===2&&relocation.every(x=>x.difference.pixels===0&&x.nativeCalls===x.glyphs),relocationScope:'single native showText interval without clips; nontext/mathematical strokes not included',semanticUnicodeCertified:false,holdoutsOpened:0,seconds:(performance.now()-begin)/1000};
fs.writeFileSync(path.join(out,'events-private.json'),JSON.stringify(events));fs.writeFileSync(path.join(out,'text-inventory-private.json'),JSON.stringify(texts));fs.writeFileSync(path.join(out,'resources-private.json'),JSON.stringify(Object.fromEntries([...resources].map(([k,r])=>[k,r.commands]))));fs.writeFileSync(path.join(out,'clips-private.json'),JSON.stringify(Object.fromEntries([...clipResources].map(([k,r])=>[k,r.svg]))));fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));await task.destroy();
