#!/usr/bin/env python3
"""Exercise artifact transfer without compiling or using any user documents."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

spec = importlib.util.spec_from_file_location("academic_ci", Path(__file__).with_name("academic-linux-ci.py"))
ci = importlib.util.module_from_spec(spec)
spec.loader.exec_module(ci)


class ArtifactTests(unittest.TestCase):
    def test_native_prerequisites_are_bounded_and_use_official_sources(self):
        workflow = Path(__file__).parents[1] / ".github/workflows/academic-linux.yml"
        step = workflow.read_text().split("      - name: Install native prerequisites\n", 1)[1].split("      - uses:", 1)[0]
        self.assertIn("timeout-minutes: 25", step)
        self.assertIn("https://archive.ubuntu.com/ubuntu", step)
        self.assertIn("https://security.ubuntu.com/ubuntu", step)
        self.assertIn("signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg", step)
        self.assertIn('Dir::Etc::sourceparts=-', step)
        self.assertIn('Acquire::https::Timeout=30', step)
        self.assertIn('Acquire::Retries=2', step)
        self.assertIn('timeout --kill-after=30s 5m apt-get', step)
        self.assertIn('--error-on=any update', step)
        self.assertIn('timeout --kill-after=30s 10m apt-get', step)
        self.assertIn('timeout --kill-after=30s 3m rustup toolchain install', step)
        self.assertIn('for attempt in 1 2', step)
        self.assertIn('[ "$attempt" = 2 ] && exit 1', step)
        shell = "\n".join(line.removeprefix("          ") for line in step.split("        run: |\n", 1)[1].splitlines())
        subprocess.run(["bash", "-n"], input=shell, text=True, check=True)

        # Run the actual workflow shell with harmless command shims. Never use apt
        # or sudo on the test host, and prove exhausted retries stop the build.
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            shims = {
                "sudo": '#!/bin/bash\nexec "$@"\n',
                "sleep": "#!/bin/bash\nexit 0\n",
                "rustup": '#!/bin/bash\necho rustup >> "$RUNNER_TEMP/calls"\n',
                "timeout": '''#!/usr/bin/env python3
import os
from pathlib import Path
import sys
root = Path(os.environ["RUNNER_TEMP"])
calls = root / "calls"
previous = calls.read_text() if calls.exists() else ""
kind = "update" if "update" in sys.argv else "install"
calls.write_text(previous + kind + "\\n")
if kind == "update" and previous.count("update\\n") < int(os.environ["FAIL_UPDATES"]):
    sys.exit(100)
''',
            }
            for name, content in shims.items():
                (root / name).write_text(content)
                (root / name).chmod(0o755)
            for failures in [0, 1, 2]:
                (root / "calls").write_text("")
                env = dict(os.environ, RUNNER_TEMP=tmp, PATH=tmp + ":" + os.environ["PATH"], FAIL_UPDATES=str(failures))
                result = subprocess.run(["bash", "-e"], input=shell, text=True, env=env, capture_output=True)
                calls = (root / "calls").read_text().splitlines()
                self.assertEqual(calls.count("update"), min(failures + 1, 2))
                self.assertEqual(result.returncode == 0, failures < 2, result.stderr)
                self.assertEqual("install" in calls, failures < 2)
                self.assertEqual("rustup" in calls, failures < 2)

    def test_generated_outputs_do_not_allow_source_or_pin_changes(self):
        def commands(*args, **kwargs):
            if "--cached" in args:
                return ""
            if args[1] == "status":
                return " M " + ci.TURSO
            if "--name-only" in args:
                return ci.TURSO
            if "--name-status" in args:
                return self.changes
            if "rev-parse" in args:
                return self.actual if "-C" in args else "pinned"
            return "recorded diff"
        self.actual = "pinned"
        with patch.object(ci, "command", commands):
            self.changes = "D\tpermissions/autogenerated/commands/load.toml\nM\tpermissions/schemas/schema.json"
            self.assertTrue(ci.inspect_source()["passed"])
            self.actual = "different"
            self.assertFalse(ci.inspect_source()["passed"])
            self.actual = "pinned"
            self.changes += "\nM\tsrc/lib.rs"
            self.assertFalse(ci.inspect_source()["passed"])
            self.changes = "M\tpermissions/autogenerated/commands/load.toml"
            self.assertFalse(ci.inspect_source()["passed"])

    def test_export_round_trip(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            binary = root / "target/debug/readest"
            binary.parent.mkdir(parents=True)
            original = bytes(range(256)) * 100
            binary.write_bytes(original)
            binary.chmod(0o755)
            cef = root / "cef"
            (cef / "locales").mkdir(parents=True)
            for name in ci.RUNTIME + ["locales/en-US.pak"]:
                (cef / name).write_bytes(name.encode())
            for name in ["LICENSE", "Cargo.cef.lock", "pnpm-lock.yaml"]:
                (root / name).write_text(name)

            def command(*args, **kwargs):
                if "--cached" in args:
                    return ""
                if args[:2] == ("git", "status"):
                    return ""
                if args[0] == "ldd":
                    return "libcef.so => verified"
                return "synthetic-provenance"

            env = {"CEF_PATH": str(cef), "GITHUB_REPOSITORY": "example/test", "GITHUB_RUN_ID": "1"}
            with patch.object(Path, "cwd", return_value=root), patch.object(ci, "command", command), \
                    patch.dict(os.environ, env), patch.object(ci, "PART_SIZE", 1024), patch("builtins.print"):
                ci.export_artifact()
            artifact = root / "academic-linux-artifact"
            manifest = json.loads((artifact / "transfer.json").read_text())
            data = b"".join((artifact / part["name"]).read_bytes() for part in manifest["parts"])
            self.assertGreater(len(manifest["parts"]), 1)
            self.assertEqual(hashlib.sha256(data).hexdigest(), manifest["archiveSha256"])
            self.assertEqual(len(data), manifest["archiveBytes"])
            for part in manifest["parts"]:
                self.assertEqual(ci.digest(artifact / part["name"]), part["sha256"])
            archive = root / "restored.tar.gz"
            archive.write_bytes(data)
            with ci.tarfile.open(archive) as bundle:
                self.assertEqual(set(bundle.getnames()), {"readest", "LICENSE", "provenance.json"})
                self.assertEqual(bundle.extractfile("readest").read(), original)
                self.assertEqual(bundle.getmember("readest").mode, 0o755)
                provenance = json.load(bundle.extractfile("provenance.json"))
                self.assertEqual(provenance["binarySha256"], ci.digest(binary))
                self.assertEqual(provenance["cefRuntimeSha256"]["locales/en-US.pak"], ci.digest(cef / "locales/en-US.pak"))

    def test_reject_corrupt_cached_cef(self):
        with tempfile.TemporaryDirectory() as tmp:
            archive = Path(tmp) / "readest-cef-cache/cef.tar.bz2"
            archive.parent.mkdir()
            archive.write_bytes(b"corrupt archive")
            with patch.dict(os.environ, {"RUNNER_TEMP": tmp}):
                with self.assertRaisesRegex(RuntimeError, "checksum mismatch"):
                    ci.prepare_cef()


if __name__ == "__main__":
    unittest.main()
