import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {createServer} from 'node:http';
import {fileURLToPath} from 'node:url';
const base=new URL('.',import.meta.url),html=await readFile(new URL('index.html',base),'utf8'),manifest=JSON.parse(await readFile(new URL('source-manifest.json',base),'utf8'));
assert.equal(createHash('sha256').update(html).digest('hex'),manifest.html_sha256);
const match=html.match(/<script id="page-data" type="application\/json">([\s\S]*?)<\/script>/);assert.ok(match);const pages=JSON.parse(match[1]);assert.equal(pages.length,2);assert.equal(pages[0].refused,false);assert.equal(pages[1].refused,true);assert.equal(pages[0].pieces.length,7);assert.ok(pages.every(p=>p.source.startsWith('data:image/png;base64,')&&p.pieces.every(x=>x.source.startsWith('data:image/png;base64,')&&x.display.startsWith('data:image/png;base64,'))));assert.ok(!html.includes('fetch('));assert.ok(!/https?:\/\//.test(html));
if(process.argv.includes('--check-fixture')){console.log('Original embedded fixture hashes and page modes passed. No browser claim.');process.exit(0);}
const {chromium,expect}=await import('@playwright/test');const {PNG}=await import('pngjs');const output=new URL('evidence/',base);await mkdir(output,{recursive:true});const server=createServer((req,res)=>{if(req.url==='/favicon.ico'){res.writeHead(204);res.end();return;}res.writeHead(req.url==='/'?200:404,{'Content-Type':'text/html; charset=utf-8'});res.end(req.url==='/'?html:'Not found');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;let browser,context,page;const errors=[],checks=[],report={manifest,checks,scope:'Original synthetic fixture and sandboxed Chromium UI only'};const check=async(name,f)=>{await f();checks.push(name);console.log('PASS '+name);};const decoded=()=>page.evaluate(async()=>{await Promise.all([...document.images].filter(i=>i.src).map(i=>i.decode()));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));});const shot=async(name)=>{await decoded();await page.screenshot({path:fileURLToPath(new URL(name+'.png',output)),fullPage:true});};const noOverflow=async()=>assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+1),true);
try{
 browser=await chromium.launch({headless:true,chromiumSandbox:true});report.chromiumVersion=browser.version();context=await browser.newContext({viewport:{width:1280,height:900},serviceWorkers:'block'});await context.route('**/*',route=>{if(new URL(route.request().url()).origin!==origin){errors.push('Unexpected request '+route.request().url());return route.abort();}return route.continue();});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(origin,{waitUntil:'load'});
 await check('native image pieces decode and fixed width',async()=>{await decoded();await expect(page.locator('.piece')).toHaveCount(7);await expect(page.locator('#reader')).toHaveCSS('width','390px');await noOverflow();});await shot('desktop-native');
 await check('formula source zoom, context anchor and keyboard return',async()=>{const button=page.locator('.piece').nth(3).locator('button');await button.click();await expect(page.locator('#source')).toBeVisible();await decoded();assert.equal(await page.locator('#source-image').evaluate(i=>i.naturalWidth),pages[0].pieces[3].bbox[2]-pages[0].pieces[3].bbox[0]);await page.locator('#scale').fill('100');await page.locator('#scale').dispatchEvent('input');await expect(page.locator('#percent')).toHaveText('100%');await expect(page.locator('#source-image')).toHaveCSS('width',pages[0].pieces[3].bbox[2]-pages[0].pieces[3].bbox[0]+'px');await shot('formula-source-zoom');await page.locator('#context').click();await decoded();await expect(page.locator('#highlight')).toBeVisible();assert.equal(await page.locator('#source-image').evaluate(i=>i.naturalWidth),1920);await shot('formula-original-location');await page.keyboard.press('Escape');await expect(page.locator('#source')).toBeHidden();await expect(button).toBeFocused();});
 await check('figure colors remain visible in enlarged original crop',async()=>{await page.locator('.piece').nth(4).locator('button').click();await decoded();const png=PNG.sync.read(await page.locator('#source-image').screenshot());let blue=0,orange=0;for(let i=0;i<png.data.length;i+=4){if(png.data[i+2]>png.data[i]*1.5&&png.data[i+2]>100)blue++;if(png.data[i]>png.data[i+2]*1.5&&png.data[i]>100)orange++;}assert.ok(blue>100&&orange>100,JSON.stringify({blue,orange}));await page.locator('#close').click();});
 await check('scan fallback remains explicit and full source opens',async()=>{await page.locator('#page').selectOption('1');await expect(page.locator('.piece')).toHaveCount(1);await expect(page.locator('.source-only')).toContainText('本页保留原版');await page.locator('#original').click();await decoded();await expect(page.locator('#context')).toBeHidden();await expect(page.locator('#source')).toBeVisible();await page.locator('#close').click();});
 await check('mobile no overflow, repeat zoom and page return',async()=>{await page.setViewportSize({width:390,height:844});await page.locator('#page').selectOption('0');await decoded();await noOverflow();await shot('mobile-native');for(let i=0;i<2;i++){await page.locator('.piece').nth(4).locator('button').click();await decoded();await expect(page.locator('#source')).toBeVisible();await noOverflow();if(i===0)await shot('mobile-source-zoom');await page.keyboard.press('Escape');}await page.locator('#page').selectOption('1');await shot('mobile-original-fallback');});
 assert.deepEqual(errors,[]);report.status='passed';
}catch(e){report.status='failed';report.error=e.stack||String(e);process.exitCode=1;if(page)await shot('failure').catch(()=>{});}finally{report.browserErrors=errors;await writeFile(new URL('report.json',output),JSON.stringify(report,null,2));await context?.close();await browser?.close();await new Promise(resolve=>server.close(resolve));console.log(JSON.stringify(report,null,2));}
